apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.app.name }}
spec:
  host: {{ .Values.app.name }}.apps.cs220tanirvan.f41x.p1.openshiftapps.com
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .Values.app.name }}
    weight: 100
  wildcardPolicy: None
